config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:create]
    resources :reviews, only: [:create]
  end
  delete "/bookmarks/:id", to: "bookmarks#destroy", as: :bookmark
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :content, presence: true
  validates :rating, inclusion: { in: (1..5) }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # def new
  #   @bookmark = Bookmark.new
  #   @list = List.find(params[:list_id])
  # end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="container my-5">
    <div class="row justify-content-md-center">
      <div class="col-6 bg-white p-3">
        <h1 class= "mb-3">Add to <%= @list.name %></h1>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment %>
          <%= f.association :movie %>
          <%= f.button :submit, "Add movie", class: "btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "https://logopond.com/logos/86ffa8e0c1b92930e00dbea6ffa619f9.png" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/lists/new">Add list</a>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars.githubusercontent.com/u/77209045?v=4", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My lists", "/", class: "dropdown-item" %>
              <%= link_to "New list", "/lists/new", class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1594909122845-11baa439b7bf?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80');">
  <div class="container">
    <h1>MovieList</h1>
    <p>Easily keep track of your favorite movies.</p>
  </div>
</div>

<div class="container my-5">
  <div class="row my-3">
    <div class="col">
       <h1>My Lists</h1>
    </div>
  </div>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-sm-12 col-md-6 mb-3">
        <%= link_to list_path(list) do  %>
          <div class="card-category" data-aos="fade-up" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
            <%= list.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container my-5">
  <div class="row justify-content-md-center">
    <div class="col-6 bg-white p-3">
      <h1 class= "mb-3">Create new list</h1>
       <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, "Create a list", class: "btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key %>')">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<p class="text-center my-5">
  <a class="btn btn-flat" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Add movie
  </a>
</p>
<div class="collapse" id="collapseExample">
  <div class="container">
    <div class="container my-5">
      <div class="row justify-content-center">
        <div class="col-sm-8 col-md-6 bg-white p-3">
          <h1 class= "mb-3 text-center">Add to <%= @list.name %></h1>
          <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.input :comment %>
            <%= f.association :movie %>
            <%= f.button :submit, "Add to list", class: "btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container my-5">
  <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-sm-12 col-md-6 mb-3">
        <div class="card card-movie" data-aos="fade-up">
          <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="<%= bookmark.movie.title %> movie poster">
          <div class="card-body">
            <div class="card-title d-flex justify-content-between">
              <h5><%= bookmark.movie.title %></h5>
              <span><%= bookmark.movie.rating %> <i class="fas fa-star"></i></span>
            </div>
            <p class="card-overview"><%= bookmark.movie.overview %></p>
            <div class="card-comment d-flex justify-content-between pt-3">
              <p class="m-0"><i class="fas fa-quote-left"></i> <em><%= bookmark.comment %></em></p>
              <%= link_to bookmark_path(bookmark), method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="my-5 text-center">
    <%= link_to "Back to lists", root_path, { class: "btn btn-primary"} %>
  </div>
  <hr>
  <div class="reviews d-flex justify-content-between mt-5">
    <div class="review-list pr-3 w-50">
      <h3 class="mb-3">Reviews</h3>
      <% @list.reviews.each do |review| %>
        <div class="stars d-flex align-items-center mb-1">
          <div class="stars-fontawesome">
            <% review.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
          </div>
          <div class="timestamp pl-3">
            <p class="m-0"><em>posted <%= ((Time.now - review.created_at) / 60).floor %> minutes ago</em></p>
          </div>
        </div>
        <p><%= review.content %></p>
        <hr>
      <% end %>
    </div>
    <div class="review-form w-50">
      <div class="bg-white p-3">
        <h4 class= "mb-3">Add your review</h4>
          <%= simple_form_for [@list, @review] do |f| %>
            <%= f.input :content, label: "Comment"%>
            <%= f.input :rating, collection: 1..5 %>
            <%= f.button :submit, class: "btn-flat" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>